ID-B-10
AleksandrTrm/-PetFamily pull request #23
Opened 2024-09-28 11:11 UTC by AleksandrTrm

2024-09-28 20:19 UTC, Asasen1 commented on PetFamily.Backend/src/PetFamily.Infrastructure/Configurations/Read/VolunteerDtoConfiguration.cs
> +public class VolunteerDtoConfiguration : IEntityTypeConfiguration<VolunteerDto>
У дтошек такую полную конфигурацию писать не обязательно. Достаточно ключ указать, связи

2024-09-28 20:20 UTC, Asasen1 approved these changes
Атлишна

2024-09-28 20:26 UTC, YADARAN1 requested changes

2024-09-28 20:26 UTC, YADARAN1 commented on PetFamily.Backend/src/PetFamily.Domain/VolunteersManagement/Entities/Pets/Pet.cs
> +            Guid speciesId,
У нас было задание сделать VO состоящее из SpeciesId SpeciesId и Guid BreedId + ты сделал всё наоборот

2024-09-30 08:03 UTC, YADARAN1 approved these changes

2024-09-30 13:59 UTC, merged