ID-B-4_4
AleksandrTrm/-PetFamily pull request #9
Opened 2024-08-22 17:06 UTC by AleksandrTrm

2024-08-22 18:36 UTC, KirillSachkov requested changes

2024-08-22 18:36 UTC, KirillSachkov commented on PetFamily.Backend/src/PetFamily.Domain/Entities/SpeciesAggregate/Breeds/BreedId.cs
> +    private BreedId()
для value object не нужен пустой конструктор

2024-08-22 18:36 UTC, KirillSachkov commented on PetFamily.Backend/src/PetFamily.Domain/Entities/Volunteers/Volunteer/Volunteer.cs
> +        public Volunteer(VolunteerId id, FullName fullFullName, Description description, int experience,
каждый параметр должен быть на своей строке

2024-08-22 18:36 UTC, KirillSachkov commented on PetFamily.Backend/src/PetFamily.Domain/Entities/Volunteers/Volunteer/Volunteer.cs
> +        public static Result<Volunteer, string> Create(VolunteerId id, FullName fullFullName, Description description, int experience,
здесь тоже, поправить нужно везде

2024-08-22 18:36 UTC, KirillSachkov commented on PetFamily.Backend/src/PetFamily.Domain/Entities/Volunteers/Volunteer/VolunteerId.cs
> +    private VolunteerId()
пустой конструктор в value objects не нужен

2024-08-22 18:48 UTC, YADARAN1 requested changes

2024-08-22 18:48 UTC, YADARAN1 commented on PetFamily.Backend/src/PetFamily.Domain/Entities/SpeciesAggregate/Species/Species.cs
> +    public List<Breed> Breeds { get; private set; }
убрать private set

2024-08-22 18:48 UTC, YADARAN1 commented on PetFamily.Backend/src/PetFamily.Domain/Entities/Volunteers/Pets/Pet.cs
> +        private Pet(PetId id, Nickname nickname, SpeciesBreed speciesBreed, Description description, string breed,
каждое свойство на новой строке

2024-08-22 18:48 UTC, YADARAN1 commented on PetFamily.Backend/src/PetFamily.Domain/Entities/Volunteers/Pets/Pet.cs
> +        public static Result<Pet, string> Create(PetId id, Nickname nickname, SpeciesBreed speciesBreed,
каждое свойство на новой строке

2024-08-22 18:48 UTC, YADARAN1 commented on PetFamily.Backend/src/PetFamily.Domain/Entities/Volunteers/Pets/Pet.cs
> +            return new Pet(id, nickname, speciesBreed, description, breed, color, healthInfo, address, weight, height,
каждое свойство на новой строке

2024-08-22 18:48 UTC, YADARAN1 commented on PetFamily.Backend/src/PetFamily.Domain/Entities/Volunteers/Pets/PetId.cs
> +    public Guid Value { get; private set; }
private set убрать

2024-08-22 18:48 UTC, YADARAN1 commented on PetFamily.Backend/src/PetFamily.Domain/Entities/SpeciesAggregate/Species/SpeciesId.cs
> +    public Guid Value { get; private set; }
private set убрать

2024-08-22 18:48 UTC, YADARAN1 commented on PetFamily.Backend/src/PetFamily.Domain/Entities/SpeciesAggregate/Breeds/BreedId.cs
> +    public Guid Value { get; private set; }
private set убрать

2024-08-22 18:48 UTC, YADARAN1 commented on PetFamily.Backend/src/PetFamily.Domain/Entities/Volunteers/Volunteer/Volunteer.cs
> +        public Volunteer(VolunteerId id, FullName fullFullName, Description description, int experience,
каждое свойство на новой строке

2024-08-22 18:48 UTC, YADARAN1 commented on PetFamily.Backend/src/PetFamily.Domain/Entities/Volunteers/Volunteer/Volunteer.cs
> +        public static Result<Volunteer, string> Create(VolunteerId id, FullName fullFullName, Description description, int experience,
каждое свойство на новой строке

2024-08-22 18:48 UTC, YADARAN1 commented on PetFamily.Backend/src/PetFamily.Domain/Entities/Volunteers/Volunteer/VolunteerId.cs
> +    public Guid Value { get; private set; }
private set убрать

2024-08-22 18:48 UTC, YADARAN1 commented on PetFamily.Backend/src/PetFamily.Domain/Shared/Entity.cs
> +    protected Entity(TId id) { }
protected Entity(TId id) => Id = id

2024-08-22 18:48 UTC, YADARAN1 commented on PetFamily.Backend/src/PetFamily.Domain/ValueObjects/PetValueObjects/SpeciesBreed.cs
> +    public BreedId BreedId { get; private set; }
BreedId это должен быть просто Guid BreedId, и private set убрать везде, перечитай ещё раз задание

2024-08-22 18:48 UTC, YADARAN1 commented on PetFamily.Backend/src/PetFamily.Domain/ValueObjects/PetValueObjects/SpeciesBreed.cs
> +    private SpeciesBreed()
у рекордов не должно быть 2 конструктора

2024-08-22 18:48 UTC, YADARAN1 commented on PetFamily.Backend/src/PetFamily.Domain/ValueObjects/PetValueObjects/SpeciesBreed.cs
> +    public SpeciesBreed(SpeciesId speciesId, BreedId breedId)
поменять на приватный, т.к. VO

2024-08-22 18:48 UTC, YADARAN1 commented on PetFamily.Backend/src/PetFamily.Infrastructure/Configurations/PetConfiguration.cs
> +        builder.Property(p => p.Id)
в конфигурациях нет метода ToTable, добавить

2024-08-22 18:48 UTC, YADARAN1 commented on PetFamily.Backend/src/PetFamily.Infrastructure/Configurations/SpeciesConfiguration.cs
> +        builder.HasKey(s => s.Id);
в конфигурациях нет метода ToTable, добавить

2024-08-22 18:48 UTC, YADARAN1 commented on PetFamily.Backend/src/PetFamily.Infrastructure/Configurations/VolunteerConfiguration.cs
> +        builder.Property(v => v.Id)
в конфигурациях нет метода ToTable, добавить

2024-08-22 18:48 UTC, YADARAN1 commented on PetFamily.Backend/src/PetFamily.Infrastructure/Configurations/BreedConfiguration.cs
> +        builder.HasKey(b => b.Id);
в конфигурациях нет метода ToTable, добавить

2024-08-23 08:48 UTC, KirillSachkov requested changes

2024-08-23 08:48 UTC, KirillSachkov commented on PetFamily.Backend/src/PetFamily.Domain/ValueObjects/Description.cs
> +    private Description()
Не работает потому что у тебя в конструкторе параметр называется description, а нужно value. Имена свойства и параметров должны совпадать

2024-08-23 08:48 UTC, KirillSachkov commented on PetFamily.Backend/src/PetFamily.Domain/ValueObjects/Description.cs
> +    private Description()
поправь это везде

2024-08-24 09:27 UTC, KirillSachkov approved these changes

2024-08-24 09:27 UTC, merged